/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_FUSEDirFil */

#ifndef _Included_org_catacombae_jfuse_FUSEDirFil
#define _Included_org_catacombae_jfuse_FUSEDirFil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_FUSEDirFil
 * Method:    fillNative
 * Signature: ([B[BIJ)I
 */
JNIEXPORT jint JNICALL Java_org_catacombae_jfuse_FUSEDirFil_fillNative
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jlong);

/*
 * Class:     org_catacombae_jfuse_FUSEDirFil
 * Method:    freeNative
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_catacombae_jfuse_FUSEDirFil_freeNative
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
