/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_types_system_Errno */

#ifndef _Included_org_catacombae_jfuse_types_system_Errno
#define _Included_org_catacombae_jfuse_types_system_Errno
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_types_system_Errno
 * Method:    getNativeErrnoValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_catacombae_jfuse_types_system_Errno_getNativeErrnoValue
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
