/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_FUSE */

#ifndef _Included_org_catacombae_jfuse_FUSE
#define _Included_org_catacombae_jfuse_FUSE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_FUSE
 * Method:    mountNative26
 * Signature: (Lorg/catacombae/jfuse/FUSE26FileSystem;Ljava/lang/String;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_catacombae_jfuse_FUSE_mountNative26
  (JNIEnv *, jclass, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
