/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_FUSEFillDir */

#ifndef _Included_org_catacombae_jfuse_FUSEFillDir
#define _Included_org_catacombae_jfuse_FUSEFillDir
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_FUSEFillDir
 * Method:    fillNative
 * Signature: ([B[BLorg/catacombae/jfuse/Stat;J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_catacombae_jfuse_FUSEFillDir_fillNative
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
