/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_types_system_StatConstant */

#ifndef _Included_org_catacombae_jfuse_types_system_StatConstant
#define _Included_org_catacombae_jfuse_types_system_StatConstant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_types_system_StatConstant
 * Method:    getNativeValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_catacombae_jfuse_types_system_StatConstant_getNativeValue
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
