/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_FUSE */

#ifndef _Included_org_catacombae_jfuse_FUSE
#define _Included_org_catacombae_jfuse_FUSE
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_FUSE
 * Method:    mountNative26
 * Signature: (Lorg/catacombae/jfuse/FUSE26FileSystem;Ljava/lang/String;[Ljava/lang/String;Lorg/catacombae/jfuse/FUSE26Capabilities;Lorg/catacombae/jfuse/MacFUSE20Capabilities;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_catacombae_jfuse_FUSE_mountNative26
  (JNIEnv *, jclass, jobject, jstring, jobjectArray, jobject, jobject);

/*
 * Class:     org_catacombae_jfuse_FUSE
 * Method:    getContextNative
 * Signature: ()Lorg/catacombae/jfuse/types/fuse26/FUSEContext;
 */
JNIEXPORT jobject JNICALL Java_org_catacombae_jfuse_FUSE_getContextNative
  (JNIEnv *, jclass);

/*
 * Class:     org_catacombae_jfuse_FUSE
 * Method:    unmountNative
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_catacombae_jfuse_FUSE_unmountNative
  (JNIEnv *, jclass, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
