/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_util_FUSEUtil */

#ifndef _Included_org_catacombae_jfuse_util_FUSEUtil
#define _Included_org_catacombae_jfuse_util_FUSEUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_util_FUSEUtil
 * Method:    getProcessUidNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_catacombae_jfuse_util_FUSEUtil_getProcessUidNative
  (JNIEnv *, jclass);

/*
 * Class:     org_catacombae_jfuse_util_FUSEUtil
 * Method:    getProcessGidNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_catacombae_jfuse_util_FUSEUtil_getProcessGidNative
  (JNIEnv *, jclass);

/*
 * Class:     org_catacombae_jfuse_util_FUSEUtil
 * Method:    getProcessPidNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_catacombae_jfuse_util_FUSEUtil_getProcessPidNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
