/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_JNILoader */

#ifndef _Included_org_catacombae_jfuse_JNILoader
#define _Included_org_catacombae_jfuse_JNILoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_JNILoader
 * Method:    testLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_catacombae_jfuse_JNILoader_testLibrary
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
