/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_catacombae_jfuse_types_system_StringConstant */

#ifndef _Included_org_catacombae_jfuse_types_system_StringConstant
#define _Included_org_catacombae_jfuse_types_system_StringConstant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_catacombae_jfuse_types_system_StringConstant
 * Method:    getNativeValue
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_catacombae_jfuse_types_system_StringConstant_getNativeValue
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
